export default {
    typeTemplate:[
        {
            value:'sell',
            lable:'出售中',
        },
        {
            value:'warehouse',
            lable:'仓库中',
        },
        {
            value:'sellOut',
            lable:'售罄',
        },
        {
            value:'warning',
            lable:'库存警戒',
        },
        {
            value:'recycle',
            lable:'商品回收站',
        },
    ],
    postTemplate:[
        {
            value:'包邮',
            lable:'包邮',
        },
        {
            value:'北上广10元',
            lable:'北上广10元',
        },
        {
            value:'江浙沪5元',
            lable:'江浙沪5元',
        },
    ],
    statusOps:[
        {
            value:0,
            lable:'已结束',
        },
        {
            value:1,
            lable:'拼团中',
        },
        {
            value:2,
            lable:'未开团',
        },
    ]
}